services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  schemamanger:
    image: ghcr.io/for-run-coders/schemamanger
    container_name: schemamanger
    environment:
      - PG_HOST=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
  pulling_proxy:
    image: ghcr.io/for-run-coders/pulling_telegram_proxy
    container_name: pulling_proxy
    environment:
      - BOT_TOKEN=<INSERT BOT TOKEN HERE>
      - TIMEOUT=5
      - CONFIG_SERVICE_ADDRESS=config_service:8080
      - BOT_NAME=Test configuration
  config_service:
    image: ghcr.io/for-run-coders/config_service
    container_name: config_service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://database/postgres -schemas=bot -user=postgres -password=password -connectRetries=60 migrate
    volumes:
      - ./sql_schema:/flyway/sql
    depends_on:
      - database
