services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  service:
    image: ghcr.io/for-run-coders/schemamanger
    environment:
      - PG_HOST=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
  pulling_proxy:
    image: ghcr.io/for-run-coders/pulling_telegram_proxy
    environment:
      - BOT_TOKEN=<token>
      - TIMEOUT=5
