services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  service:
    image: somekindofmodule
    environment:
      - PG_HOST=database