services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
  service:
    image: schemamanager
    environment:
      - PG_HOST=database
      - DB_USERNAME=postgres
      - DB_PASSWORD=password